version: '2'
services:
  app-nginx:
    image: app-nginx
    build: docker/nginx/
    volumes:
      - .:/var/www/
  app-php:
    image: app-php
    build: docker/php/
    working_dir: /var/www/
    volumes:
      - .:/var/www/
